package commands;

public enum Command {

    EXIT,
    GET_ALL_COURSES,
    CREATE_COURSE,
    EDIT_COURSE,
    DELETE_COURSE,
    GET_ALL_USERS_WHO_HAS_COURSE,
    GET_ALL_COURSE_TOPICS,
    GET_USERS_WHO_PASSED_TOPIC,
    CREATE_TOPIC,
    EDIT_TOPIC,
    DELETE_TOPIC,
    GET_USER_PROFILE,
    GET_ALL_USERS,
    CREATE_USER_PROFILE,
    UPDATE_USER_PROFILE,

}
